### PR TITLE
Added editorconfig

### PR DESCRIPTION
**Pull request by ndorfin**

### CODE REVIEW

**Review by Tsikitsiky — APPROVED** [review]

**Comment by vakodrazan** [comment]
Hey, 

It so quick.

Noeline

**Comment by starjardin** [comment]
it is fantastic

**Comment by Betsimisaraka** [comment]
Hey 
It is nice
Anita

**Review by lightme-fan — APPROVED** [review]
Nice!

**Review by vakodrazan — APPROVED** [review]

**Review by starjardin — APPROVED** [review]

**Review by Voninkazo — APPROVED** [review]

**Review by rinonTen — APPROVED** [review]

**Comment by Voninkazo** [comment]
Nice Shaun!

**Review by bakozetra — APPROVED** [review]

**Review by Betsimisaraka — APPROVED** [review]

**Review by Tiaraha-funny — APPROVED** [review]

**Review by starjardin — APPROVED** [review]

**Comment by Tanosimboangy** [comment]
I see it now
Thanks for making us struggle

Jacquit

**Review by voromahery — APPROVED** [review]

**Review by Ainatiana — APPROVED** [review]

**Review by Tanosimboangy — APPROVED** [review]

**Review by Fodilahy-mena — APPROVED** [review]

**Review by mitia-anah — APPROVED** [review]
Hey,
That's looks very good

**Review by Ainatiana — APPROVED** [review]
Good job man!
keep your hard working!

**Comment by Mickaellah** [comment]
Hey,

It is cool.

Clopedia

**Review by ravinalamada — APPROVED** [review]

**Review by moro-patana — APPROVED** [review]

**Review by vahona — APPROVED** [review]

**Review by Ny-Rianala — APPROVED** [review]

**Review by Mickaellah — APPROVED** [review]

**Pull request merged**
